[package]
name = "file_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
library_types = {path = "../library_types"}
rbook = "0.3.2"
uuid = "1.3.0"
pdf = "0.8.1"